/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as ComponentsRouteRouteImport } from './routes/components/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as ComponentsIndexRouteImport } from './routes/components/index'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as ComponentsThematicRouteRouteImport } from './routes/components/thematic/route'
import { Route as AppSongsIndexRouteImport } from './routes/_app/songs/index'
import { Route as AppLibraryIndexRouteImport } from './routes/_app/library/index'
import { Route as AppCharactersIndexRouteImport } from './routes/_app/characters/index'
import { Route as AppCharactersCharacterIdRouteImport } from './routes/_app/characters/$characterId'
import { Route as AppLibrarySeriesIdIndexRouteImport } from './routes/_app/library/$seriesId/index'
import { Route as AppLibrarySeriesIdVolumeIdIndexRouteImport } from './routes/_app/library/$seriesId/$volumeId/index'
import { Route as AppLibrarySeriesIdVolumeIdChapterIdIndexRouteImport } from './routes/_app/library/$seriesId/$volumeId/$chapterId/index'
import { Route as AppLibrarySeriesIdVolumeIdChapterIdPageNumberRouteImport } from './routes/_app/library/$seriesId/$volumeId/$chapterId/$pageNumber'

const ComponentsTypographyLazyRouteImport = createFileRoute(
  '/components/typography',
)()
const ComponentsTooltipLazyRouteImport = createFileRoute(
  '/components/tooltip',
)()
const ComponentsToastLazyRouteImport = createFileRoute('/components/toast')()
const ComponentsTabsLazyRouteImport = createFileRoute('/components/tabs')()
const ComponentsSwitchLazyRouteImport = createFileRoute('/components/switch')()
const ComponentsSliderLazyRouteImport = createFileRoute('/components/slider')()
const ComponentsSkeletonLazyRouteImport = createFileRoute(
  '/components/skeleton',
)()
const ComponentsSearchLazyRouteImport = createFileRoute('/components/search')()
const ComponentsScrollAreaLazyRouteImport = createFileRoute(
  '/components/scroll-area',
)()
const ComponentsQrScannerLazyRouteImport = createFileRoute(
  '/components/qr-scanner',
)()
const ComponentsQrCodeLazyRouteImport = createFileRoute('/components/qr-code')()
const ComponentsProgressLazyRouteImport = createFileRoute(
  '/components/progress',
)()
const ComponentsPaginationLazyRouteImport = createFileRoute(
  '/components/pagination',
)()
const ComponentsMenuLazyRouteImport = createFileRoute('/components/menu')()
const ComponentsLinkLazyRouteImport = createFileRoute('/components/link')()
const ComponentsInputLazyRouteImport = createFileRoute('/components/input')()
const ComponentsIconButtonLazyRouteImport = createFileRoute(
  '/components/icon-button',
)()
const ComponentsIconLazyRouteImport = createFileRoute('/components/icon')()
const ComponentsDrawerLazyRouteImport = createFileRoute('/components/drawer')()
const ComponentsDialogLazyRouteImport = createFileRoute('/components/dialog')()
const ComponentsColorLazyRouteImport = createFileRoute('/components/color')()
const ComponentsCardLazyRouteImport = createFileRoute('/components/card')()
const ComponentsButtonLazyRouteImport = createFileRoute('/components/button')()
const ComponentsBreakpointsLazyRouteImport = createFileRoute(
  '/components/breakpoints',
)()
const ComponentsBadgeLazyRouteImport = createFileRoute('/components/badge')()
const ComponentsAudioLazyRouteImport = createFileRoute('/components/audio')()
const ComponentsAnimationLazyRouteImport = createFileRoute(
  '/components/animation',
)()
const ComponentsThematicVinesLazyRouteImport = createFileRoute(
  '/components/thematic/vines',
)()
const ComponentsThematicSinGlyphLazyRouteImport = createFileRoute(
  '/components/thematic/sin-glyph',
)()
const ComponentsThematicOrnamentLazyRouteImport = createFileRoute(
  '/components/thematic/ornament',
)()
const ComponentsThematicClockworkSpinnerLazyRouteImport = createFileRoute(
  '/components/thematic/clockwork-spinner',
)()
const ComponentsThematicClockworkOrnamentLazyRouteImport = createFileRoute(
  '/components/thematic/clockwork-ornament',
)()
const ComponentsThematicClockFaceLazyRouteImport = createFileRoute(
  '/components/thematic/clock-face',
)()

const ComponentsRouteRoute = ComponentsRouteRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsIndexRoute = ComponentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ComponentsRouteRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const ComponentsTypographyLazyRoute =
  ComponentsTypographyLazyRouteImport.update({
    id: '/typography',
    path: '/typography',
    getParentRoute: () => ComponentsRouteRoute,
  } as any).lazy(() =>
    import('./routes/components/typography.lazy').then((d) => d.Route),
  )
const ComponentsTooltipLazyRoute = ComponentsTooltipLazyRouteImport.update({
  id: '/tooltip',
  path: '/tooltip',
  getParentRoute: () => ComponentsRouteRoute,
} as any).lazy(() =>
  import('./routes/components/tooltip.lazy').then((d) => d.Route),
)
const ComponentsToastLazyRoute = ComponentsToastLazyRouteImport.update({
  id: '/toast',
  path: '/toast',
  getParentRoute: () => ComponentsRouteRoute,
} as any).lazy(() =>
  import('./routes/components/toast.lazy').then((d) => d.Route),
)
const ComponentsTabsLazyRoute = ComponentsTabsLazyRouteImport.update({
  id: '/tabs',
  path: '/tabs',
  getParentRoute: () => ComponentsRouteRoute,
} as any).lazy(() =>
  import('./routes/components/tabs.lazy').then((d) => d.Route),
)
const ComponentsSwitchLazyRoute = ComponentsSwitchLazyRouteImport.update({
  id: '/switch',
  path: '/switch',
  getParentRoute: () => ComponentsRouteRoute,
} as any).lazy(() =>
  import('./routes/components/switch.lazy').then((d) => d.Route),
)
const ComponentsSliderLazyRoute = ComponentsSliderLazyRouteImport.update({
  id: '/slider',
  path: '/slider',
  getParentRoute: () => ComponentsRouteRoute,
} as any).lazy(() =>
  import('./routes/components/slider.lazy').then((d) => d.Route),
)
const ComponentsSkeletonLazyRoute = ComponentsSkeletonLazyRouteImport.update({
  id: '/skeleton',
  path: '/skeleton',
  getParentRoute: () => ComponentsRouteRoute,
} as any).lazy(() =>
  import('./routes/components/skeleton.lazy').then((d) => d.Route),
)
const ComponentsSearchLazyRoute = ComponentsSearchLazyRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => ComponentsRouteRoute,
} as any).lazy(() =>
  import('./routes/components/search.lazy').then((d) => d.Route),
)
const ComponentsScrollAreaLazyRoute =
  ComponentsScrollAreaLazyRouteImport.update({
    id: '/scroll-area',
    path: '/scroll-area',
    getParentRoute: () => ComponentsRouteRoute,
  } as any).lazy(() =>
    import('./routes/components/scroll-area.lazy').then((d) => d.Route),
  )
const ComponentsQrScannerLazyRoute = ComponentsQrScannerLazyRouteImport.update({
  id: '/qr-scanner',
  path: '/qr-scanner',
  getParentRoute: () => ComponentsRouteRoute,
} as any).lazy(() =>
  import('./routes/components/qr-scanner.lazy').then((d) => d.Route),
)
const ComponentsQrCodeLazyRoute = ComponentsQrCodeLazyRouteImport.update({
  id: '/qr-code',
  path: '/qr-code',
  getParentRoute: () => ComponentsRouteRoute,
} as any).lazy(() =>
  import('./routes/components/qr-code.lazy').then((d) => d.Route),
)
const ComponentsProgressLazyRoute = ComponentsProgressLazyRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => ComponentsRouteRoute,
} as any).lazy(() =>
  import('./routes/components/progress.lazy').then((d) => d.Route),
)
const ComponentsPaginationLazyRoute =
  ComponentsPaginationLazyRouteImport.update({
    id: '/pagination',
    path: '/pagination',
    getParentRoute: () => ComponentsRouteRoute,
  } as any).lazy(() =>
    import('./routes/components/pagination.lazy').then((d) => d.Route),
  )
const ComponentsMenuLazyRoute = ComponentsMenuLazyRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => ComponentsRouteRoute,
} as any).lazy(() =>
  import('./routes/components/menu.lazy').then((d) => d.Route),
)
const ComponentsLinkLazyRoute = ComponentsLinkLazyRouteImport.update({
  id: '/link',
  path: '/link',
  getParentRoute: () => ComponentsRouteRoute,
} as any).lazy(() =>
  import('./routes/components/link.lazy').then((d) => d.Route),
)
const ComponentsInputLazyRoute = ComponentsInputLazyRouteImport.update({
  id: '/input',
  path: '/input',
  getParentRoute: () => ComponentsRouteRoute,
} as any).lazy(() =>
  import('./routes/components/input.lazy').then((d) => d.Route),
)
const ComponentsIconButtonLazyRoute =
  ComponentsIconButtonLazyRouteImport.update({
    id: '/icon-button',
    path: '/icon-button',
    getParentRoute: () => ComponentsRouteRoute,
  } as any).lazy(() =>
    import('./routes/components/icon-button.lazy').then((d) => d.Route),
  )
const ComponentsIconLazyRoute = ComponentsIconLazyRouteImport.update({
  id: '/icon',
  path: '/icon',
  getParentRoute: () => ComponentsRouteRoute,
} as any).lazy(() =>
  import('./routes/components/icon.lazy').then((d) => d.Route),
)
const ComponentsDrawerLazyRoute = ComponentsDrawerLazyRouteImport.update({
  id: '/drawer',
  path: '/drawer',
  getParentRoute: () => ComponentsRouteRoute,
} as any).lazy(() =>
  import('./routes/components/drawer.lazy').then((d) => d.Route),
)
const ComponentsDialogLazyRoute = ComponentsDialogLazyRouteImport.update({
  id: '/dialog',
  path: '/dialog',
  getParentRoute: () => ComponentsRouteRoute,
} as any).lazy(() =>
  import('./routes/components/dialog.lazy').then((d) => d.Route),
)
const ComponentsColorLazyRoute = ComponentsColorLazyRouteImport.update({
  id: '/color',
  path: '/color',
  getParentRoute: () => ComponentsRouteRoute,
} as any).lazy(() =>
  import('./routes/components/color.lazy').then((d) => d.Route),
)
const ComponentsCardLazyRoute = ComponentsCardLazyRouteImport.update({
  id: '/card',
  path: '/card',
  getParentRoute: () => ComponentsRouteRoute,
} as any).lazy(() =>
  import('./routes/components/card.lazy').then((d) => d.Route),
)
const ComponentsButtonLazyRoute = ComponentsButtonLazyRouteImport.update({
  id: '/button',
  path: '/button',
  getParentRoute: () => ComponentsRouteRoute,
} as any).lazy(() =>
  import('./routes/components/button.lazy').then((d) => d.Route),
)
const ComponentsBreakpointsLazyRoute =
  ComponentsBreakpointsLazyRouteImport.update({
    id: '/breakpoints',
    path: '/breakpoints',
    getParentRoute: () => ComponentsRouteRoute,
  } as any).lazy(() =>
    import('./routes/components/breakpoints.lazy').then((d) => d.Route),
  )
const ComponentsBadgeLazyRoute = ComponentsBadgeLazyRouteImport.update({
  id: '/badge',
  path: '/badge',
  getParentRoute: () => ComponentsRouteRoute,
} as any).lazy(() =>
  import('./routes/components/badge.lazy').then((d) => d.Route),
)
const ComponentsAudioLazyRoute = ComponentsAudioLazyRouteImport.update({
  id: '/audio',
  path: '/audio',
  getParentRoute: () => ComponentsRouteRoute,
} as any).lazy(() =>
  import('./routes/components/audio.lazy').then((d) => d.Route),
)
const ComponentsAnimationLazyRoute = ComponentsAnimationLazyRouteImport.update({
  id: '/animation',
  path: '/animation',
  getParentRoute: () => ComponentsRouteRoute,
} as any).lazy(() =>
  import('./routes/components/animation.lazy').then((d) => d.Route),
)
const ComponentsThematicRouteRoute = ComponentsThematicRouteRouteImport.update({
  id: '/thematic',
  path: '/thematic',
  getParentRoute: () => ComponentsRouteRoute,
} as any)
const AppSongsIndexRoute = AppSongsIndexRouteImport.update({
  id: '/songs/',
  path: '/songs/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLibraryIndexRoute = AppLibraryIndexRouteImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCharactersIndexRoute = AppCharactersIndexRouteImport.update({
  id: '/characters/',
  path: '/characters/',
  getParentRoute: () => AppRouteRoute,
} as any)
const ComponentsThematicVinesLazyRoute =
  ComponentsThematicVinesLazyRouteImport.update({
    id: '/vines',
    path: '/vines',
    getParentRoute: () => ComponentsThematicRouteRoute,
  } as any).lazy(() =>
    import('./routes/components/thematic/vines.lazy').then((d) => d.Route),
  )
const ComponentsThematicSinGlyphLazyRoute =
  ComponentsThematicSinGlyphLazyRouteImport.update({
    id: '/sin-glyph',
    path: '/sin-glyph',
    getParentRoute: () => ComponentsThematicRouteRoute,
  } as any).lazy(() =>
    import('./routes/components/thematic/sin-glyph.lazy').then((d) => d.Route),
  )
const ComponentsThematicOrnamentLazyRoute =
  ComponentsThematicOrnamentLazyRouteImport.update({
    id: '/ornament',
    path: '/ornament',
    getParentRoute: () => ComponentsThematicRouteRoute,
  } as any).lazy(() =>
    import('./routes/components/thematic/ornament.lazy').then((d) => d.Route),
  )
const ComponentsThematicClockworkSpinnerLazyRoute =
  ComponentsThematicClockworkSpinnerLazyRouteImport.update({
    id: '/clockwork-spinner',
    path: '/clockwork-spinner',
    getParentRoute: () => ComponentsThematicRouteRoute,
  } as any).lazy(() =>
    import('./routes/components/thematic/clockwork-spinner.lazy').then(
      (d) => d.Route,
    ),
  )
const ComponentsThematicClockworkOrnamentLazyRoute =
  ComponentsThematicClockworkOrnamentLazyRouteImport.update({
    id: '/clockwork-ornament',
    path: '/clockwork-ornament',
    getParentRoute: () => ComponentsThematicRouteRoute,
  } as any).lazy(() =>
    import('./routes/components/thematic/clockwork-ornament.lazy').then(
      (d) => d.Route,
    ),
  )
const ComponentsThematicClockFaceLazyRoute =
  ComponentsThematicClockFaceLazyRouteImport.update({
    id: '/clock-face',
    path: '/clock-face',
    getParentRoute: () => ComponentsThematicRouteRoute,
  } as any).lazy(() =>
    import('./routes/components/thematic/clock-face.lazy').then((d) => d.Route),
  )
const AppCharactersCharacterIdRoute =
  AppCharactersCharacterIdRouteImport.update({
    id: '/characters/$characterId',
    path: '/characters/$characterId',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppLibrarySeriesIdIndexRoute = AppLibrarySeriesIdIndexRouteImport.update({
  id: '/library/$seriesId/',
  path: '/library/$seriesId/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLibrarySeriesIdVolumeIdIndexRoute =
  AppLibrarySeriesIdVolumeIdIndexRouteImport.update({
    id: '/library/$seriesId/$volumeId/',
    path: '/library/$seriesId/$volumeId/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppLibrarySeriesIdVolumeIdChapterIdIndexRoute =
  AppLibrarySeriesIdVolumeIdChapterIdIndexRouteImport.update({
    id: '/library/$seriesId/$volumeId/$chapterId/',
    path: '/library/$seriesId/$volumeId/$chapterId/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppLibrarySeriesIdVolumeIdChapterIdPageNumberRoute =
  AppLibrarySeriesIdVolumeIdChapterIdPageNumberRouteImport.update({
    id: '/library/$seriesId/$volumeId/$chapterId/$pageNumber',
    path: '/library/$seriesId/$volumeId/$chapterId/$pageNumber',
    getParentRoute: () => AppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/components': typeof ComponentsRouteRouteWithChildren
  '/components/thematic': typeof ComponentsThematicRouteRouteWithChildren
  '/components/animation': typeof ComponentsAnimationLazyRoute
  '/components/audio': typeof ComponentsAudioLazyRoute
  '/components/badge': typeof ComponentsBadgeLazyRoute
  '/components/breakpoints': typeof ComponentsBreakpointsLazyRoute
  '/components/button': typeof ComponentsButtonLazyRoute
  '/components/card': typeof ComponentsCardLazyRoute
  '/components/color': typeof ComponentsColorLazyRoute
  '/components/dialog': typeof ComponentsDialogLazyRoute
  '/components/drawer': typeof ComponentsDrawerLazyRoute
  '/components/icon': typeof ComponentsIconLazyRoute
  '/components/icon-button': typeof ComponentsIconButtonLazyRoute
  '/components/input': typeof ComponentsInputLazyRoute
  '/components/link': typeof ComponentsLinkLazyRoute
  '/components/menu': typeof ComponentsMenuLazyRoute
  '/components/pagination': typeof ComponentsPaginationLazyRoute
  '/components/progress': typeof ComponentsProgressLazyRoute
  '/components/qr-code': typeof ComponentsQrCodeLazyRoute
  '/components/qr-scanner': typeof ComponentsQrScannerLazyRoute
  '/components/scroll-area': typeof ComponentsScrollAreaLazyRoute
  '/components/search': typeof ComponentsSearchLazyRoute
  '/components/skeleton': typeof ComponentsSkeletonLazyRoute
  '/components/slider': typeof ComponentsSliderLazyRoute
  '/components/switch': typeof ComponentsSwitchLazyRoute
  '/components/tabs': typeof ComponentsTabsLazyRoute
  '/components/toast': typeof ComponentsToastLazyRoute
  '/components/tooltip': typeof ComponentsTooltipLazyRoute
  '/components/typography': typeof ComponentsTypographyLazyRoute
  '/components/': typeof ComponentsIndexRoute
  '/characters/$characterId': typeof AppCharactersCharacterIdRoute
  '/components/thematic/clock-face': typeof ComponentsThematicClockFaceLazyRoute
  '/components/thematic/clockwork-ornament': typeof ComponentsThematicClockworkOrnamentLazyRoute
  '/components/thematic/clockwork-spinner': typeof ComponentsThematicClockworkSpinnerLazyRoute
  '/components/thematic/ornament': typeof ComponentsThematicOrnamentLazyRoute
  '/components/thematic/sin-glyph': typeof ComponentsThematicSinGlyphLazyRoute
  '/components/thematic/vines': typeof ComponentsThematicVinesLazyRoute
  '/characters/': typeof AppCharactersIndexRoute
  '/library/': typeof AppLibraryIndexRoute
  '/songs/': typeof AppSongsIndexRoute
  '/library/$seriesId/': typeof AppLibrarySeriesIdIndexRoute
  '/library/$seriesId/$volumeId/': typeof AppLibrarySeriesIdVolumeIdIndexRoute
  '/library/$seriesId/$volumeId/$chapterId/$pageNumber': typeof AppLibrarySeriesIdVolumeIdChapterIdPageNumberRoute
  '/library/$seriesId/$volumeId/$chapterId/': typeof AppLibrarySeriesIdVolumeIdChapterIdIndexRoute
}
export interface FileRoutesByTo {
  '/components/thematic': typeof ComponentsThematicRouteRouteWithChildren
  '/components/animation': typeof ComponentsAnimationLazyRoute
  '/components/audio': typeof ComponentsAudioLazyRoute
  '/components/badge': typeof ComponentsBadgeLazyRoute
  '/components/breakpoints': typeof ComponentsBreakpointsLazyRoute
  '/components/button': typeof ComponentsButtonLazyRoute
  '/components/card': typeof ComponentsCardLazyRoute
  '/components/color': typeof ComponentsColorLazyRoute
  '/components/dialog': typeof ComponentsDialogLazyRoute
  '/components/drawer': typeof ComponentsDrawerLazyRoute
  '/components/icon': typeof ComponentsIconLazyRoute
  '/components/icon-button': typeof ComponentsIconButtonLazyRoute
  '/components/input': typeof ComponentsInputLazyRoute
  '/components/link': typeof ComponentsLinkLazyRoute
  '/components/menu': typeof ComponentsMenuLazyRoute
  '/components/pagination': typeof ComponentsPaginationLazyRoute
  '/components/progress': typeof ComponentsProgressLazyRoute
  '/components/qr-code': typeof ComponentsQrCodeLazyRoute
  '/components/qr-scanner': typeof ComponentsQrScannerLazyRoute
  '/components/scroll-area': typeof ComponentsScrollAreaLazyRoute
  '/components/search': typeof ComponentsSearchLazyRoute
  '/components/skeleton': typeof ComponentsSkeletonLazyRoute
  '/components/slider': typeof ComponentsSliderLazyRoute
  '/components/switch': typeof ComponentsSwitchLazyRoute
  '/components/tabs': typeof ComponentsTabsLazyRoute
  '/components/toast': typeof ComponentsToastLazyRoute
  '/components/tooltip': typeof ComponentsTooltipLazyRoute
  '/components/typography': typeof ComponentsTypographyLazyRoute
  '/': typeof AppIndexRoute
  '/components': typeof ComponentsIndexRoute
  '/characters/$characterId': typeof AppCharactersCharacterIdRoute
  '/components/thematic/clock-face': typeof ComponentsThematicClockFaceLazyRoute
  '/components/thematic/clockwork-ornament': typeof ComponentsThematicClockworkOrnamentLazyRoute
  '/components/thematic/clockwork-spinner': typeof ComponentsThematicClockworkSpinnerLazyRoute
  '/components/thematic/ornament': typeof ComponentsThematicOrnamentLazyRoute
  '/components/thematic/sin-glyph': typeof ComponentsThematicSinGlyphLazyRoute
  '/components/thematic/vines': typeof ComponentsThematicVinesLazyRoute
  '/characters': typeof AppCharactersIndexRoute
  '/library': typeof AppLibraryIndexRoute
  '/songs': typeof AppSongsIndexRoute
  '/library/$seriesId': typeof AppLibrarySeriesIdIndexRoute
  '/library/$seriesId/$volumeId': typeof AppLibrarySeriesIdVolumeIdIndexRoute
  '/library/$seriesId/$volumeId/$chapterId/$pageNumber': typeof AppLibrarySeriesIdVolumeIdChapterIdPageNumberRoute
  '/library/$seriesId/$volumeId/$chapterId': typeof AppLibrarySeriesIdVolumeIdChapterIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/components': typeof ComponentsRouteRouteWithChildren
  '/components/thematic': typeof ComponentsThematicRouteRouteWithChildren
  '/components/animation': typeof ComponentsAnimationLazyRoute
  '/components/audio': typeof ComponentsAudioLazyRoute
  '/components/badge': typeof ComponentsBadgeLazyRoute
  '/components/breakpoints': typeof ComponentsBreakpointsLazyRoute
  '/components/button': typeof ComponentsButtonLazyRoute
  '/components/card': typeof ComponentsCardLazyRoute
  '/components/color': typeof ComponentsColorLazyRoute
  '/components/dialog': typeof ComponentsDialogLazyRoute
  '/components/drawer': typeof ComponentsDrawerLazyRoute
  '/components/icon': typeof ComponentsIconLazyRoute
  '/components/icon-button': typeof ComponentsIconButtonLazyRoute
  '/components/input': typeof ComponentsInputLazyRoute
  '/components/link': typeof ComponentsLinkLazyRoute
  '/components/menu': typeof ComponentsMenuLazyRoute
  '/components/pagination': typeof ComponentsPaginationLazyRoute
  '/components/progress': typeof ComponentsProgressLazyRoute
  '/components/qr-code': typeof ComponentsQrCodeLazyRoute
  '/components/qr-scanner': typeof ComponentsQrScannerLazyRoute
  '/components/scroll-area': typeof ComponentsScrollAreaLazyRoute
  '/components/search': typeof ComponentsSearchLazyRoute
  '/components/skeleton': typeof ComponentsSkeletonLazyRoute
  '/components/slider': typeof ComponentsSliderLazyRoute
  '/components/switch': typeof ComponentsSwitchLazyRoute
  '/components/tabs': typeof ComponentsTabsLazyRoute
  '/components/toast': typeof ComponentsToastLazyRoute
  '/components/tooltip': typeof ComponentsTooltipLazyRoute
  '/components/typography': typeof ComponentsTypographyLazyRoute
  '/_app/': typeof AppIndexRoute
  '/components/': typeof ComponentsIndexRoute
  '/_app/characters/$characterId': typeof AppCharactersCharacterIdRoute
  '/components/thematic/clock-face': typeof ComponentsThematicClockFaceLazyRoute
  '/components/thematic/clockwork-ornament': typeof ComponentsThematicClockworkOrnamentLazyRoute
  '/components/thematic/clockwork-spinner': typeof ComponentsThematicClockworkSpinnerLazyRoute
  '/components/thematic/ornament': typeof ComponentsThematicOrnamentLazyRoute
  '/components/thematic/sin-glyph': typeof ComponentsThematicSinGlyphLazyRoute
  '/components/thematic/vines': typeof ComponentsThematicVinesLazyRoute
  '/_app/characters/': typeof AppCharactersIndexRoute
  '/_app/library/': typeof AppLibraryIndexRoute
  '/_app/songs/': typeof AppSongsIndexRoute
  '/_app/library/$seriesId/': typeof AppLibrarySeriesIdIndexRoute
  '/_app/library/$seriesId/$volumeId/': typeof AppLibrarySeriesIdVolumeIdIndexRoute
  '/_app/library/$seriesId/$volumeId/$chapterId/$pageNumber': typeof AppLibrarySeriesIdVolumeIdChapterIdPageNumberRoute
  '/_app/library/$seriesId/$volumeId/$chapterId/': typeof AppLibrarySeriesIdVolumeIdChapterIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/components'
    | '/components/thematic'
    | '/components/animation'
    | '/components/audio'
    | '/components/badge'
    | '/components/breakpoints'
    | '/components/button'
    | '/components/card'
    | '/components/color'
    | '/components/dialog'
    | '/components/drawer'
    | '/components/icon'
    | '/components/icon-button'
    | '/components/input'
    | '/components/link'
    | '/components/menu'
    | '/components/pagination'
    | '/components/progress'
    | '/components/qr-code'
    | '/components/qr-scanner'
    | '/components/scroll-area'
    | '/components/search'
    | '/components/skeleton'
    | '/components/slider'
    | '/components/switch'
    | '/components/tabs'
    | '/components/toast'
    | '/components/tooltip'
    | '/components/typography'
    | '/components/'
    | '/characters/$characterId'
    | '/components/thematic/clock-face'
    | '/components/thematic/clockwork-ornament'
    | '/components/thematic/clockwork-spinner'
    | '/components/thematic/ornament'
    | '/components/thematic/sin-glyph'
    | '/components/thematic/vines'
    | '/characters/'
    | '/library/'
    | '/songs/'
    | '/library/$seriesId/'
    | '/library/$seriesId/$volumeId/'
    | '/library/$seriesId/$volumeId/$chapterId/$pageNumber'
    | '/library/$seriesId/$volumeId/$chapterId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/components/thematic'
    | '/components/animation'
    | '/components/audio'
    | '/components/badge'
    | '/components/breakpoints'
    | '/components/button'
    | '/components/card'
    | '/components/color'
    | '/components/dialog'
    | '/components/drawer'
    | '/components/icon'
    | '/components/icon-button'
    | '/components/input'
    | '/components/link'
    | '/components/menu'
    | '/components/pagination'
    | '/components/progress'
    | '/components/qr-code'
    | '/components/qr-scanner'
    | '/components/scroll-area'
    | '/components/search'
    | '/components/skeleton'
    | '/components/slider'
    | '/components/switch'
    | '/components/tabs'
    | '/components/toast'
    | '/components/tooltip'
    | '/components/typography'
    | '/'
    | '/components'
    | '/characters/$characterId'
    | '/components/thematic/clock-face'
    | '/components/thematic/clockwork-ornament'
    | '/components/thematic/clockwork-spinner'
    | '/components/thematic/ornament'
    | '/components/thematic/sin-glyph'
    | '/components/thematic/vines'
    | '/characters'
    | '/library'
    | '/songs'
    | '/library/$seriesId'
    | '/library/$seriesId/$volumeId'
    | '/library/$seriesId/$volumeId/$chapterId/$pageNumber'
    | '/library/$seriesId/$volumeId/$chapterId'
  id:
    | '__root__'
    | '/_app'
    | '/components'
    | '/components/thematic'
    | '/components/animation'
    | '/components/audio'
    | '/components/badge'
    | '/components/breakpoints'
    | '/components/button'
    | '/components/card'
    | '/components/color'
    | '/components/dialog'
    | '/components/drawer'
    | '/components/icon'
    | '/components/icon-button'
    | '/components/input'
    | '/components/link'
    | '/components/menu'
    | '/components/pagination'
    | '/components/progress'
    | '/components/qr-code'
    | '/components/qr-scanner'
    | '/components/scroll-area'
    | '/components/search'
    | '/components/skeleton'
    | '/components/slider'
    | '/components/switch'
    | '/components/tabs'
    | '/components/toast'
    | '/components/tooltip'
    | '/components/typography'
    | '/_app/'
    | '/components/'
    | '/_app/characters/$characterId'
    | '/components/thematic/clock-face'
    | '/components/thematic/clockwork-ornament'
    | '/components/thematic/clockwork-spinner'
    | '/components/thematic/ornament'
    | '/components/thematic/sin-glyph'
    | '/components/thematic/vines'
    | '/_app/characters/'
    | '/_app/library/'
    | '/_app/songs/'
    | '/_app/library/$seriesId/'
    | '/_app/library/$seriesId/$volumeId/'
    | '/_app/library/$seriesId/$volumeId/$chapterId/$pageNumber'
    | '/_app/library/$seriesId/$volumeId/$chapterId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  ComponentsRouteRoute: typeof ComponentsRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/components': {
      id: '/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/': {
      id: '/components/'
      path: '/'
      fullPath: '/components/'
      preLoaderRoute: typeof ComponentsIndexRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/components/typography': {
      id: '/components/typography'
      path: '/typography'
      fullPath: '/components/typography'
      preLoaderRoute: typeof ComponentsTypographyLazyRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/tooltip': {
      id: '/components/tooltip'
      path: '/tooltip'
      fullPath: '/components/tooltip'
      preLoaderRoute: typeof ComponentsTooltipLazyRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/toast': {
      id: '/components/toast'
      path: '/toast'
      fullPath: '/components/toast'
      preLoaderRoute: typeof ComponentsToastLazyRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/tabs': {
      id: '/components/tabs'
      path: '/tabs'
      fullPath: '/components/tabs'
      preLoaderRoute: typeof ComponentsTabsLazyRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/switch': {
      id: '/components/switch'
      path: '/switch'
      fullPath: '/components/switch'
      preLoaderRoute: typeof ComponentsSwitchLazyRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/slider': {
      id: '/components/slider'
      path: '/slider'
      fullPath: '/components/slider'
      preLoaderRoute: typeof ComponentsSliderLazyRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/skeleton': {
      id: '/components/skeleton'
      path: '/skeleton'
      fullPath: '/components/skeleton'
      preLoaderRoute: typeof ComponentsSkeletonLazyRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/search': {
      id: '/components/search'
      path: '/search'
      fullPath: '/components/search'
      preLoaderRoute: typeof ComponentsSearchLazyRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/scroll-area': {
      id: '/components/scroll-area'
      path: '/scroll-area'
      fullPath: '/components/scroll-area'
      preLoaderRoute: typeof ComponentsScrollAreaLazyRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/qr-scanner': {
      id: '/components/qr-scanner'
      path: '/qr-scanner'
      fullPath: '/components/qr-scanner'
      preLoaderRoute: typeof ComponentsQrScannerLazyRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/qr-code': {
      id: '/components/qr-code'
      path: '/qr-code'
      fullPath: '/components/qr-code'
      preLoaderRoute: typeof ComponentsQrCodeLazyRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/progress': {
      id: '/components/progress'
      path: '/progress'
      fullPath: '/components/progress'
      preLoaderRoute: typeof ComponentsProgressLazyRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/pagination': {
      id: '/components/pagination'
      path: '/pagination'
      fullPath: '/components/pagination'
      preLoaderRoute: typeof ComponentsPaginationLazyRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/menu': {
      id: '/components/menu'
      path: '/menu'
      fullPath: '/components/menu'
      preLoaderRoute: typeof ComponentsMenuLazyRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/link': {
      id: '/components/link'
      path: '/link'
      fullPath: '/components/link'
      preLoaderRoute: typeof ComponentsLinkLazyRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/input': {
      id: '/components/input'
      path: '/input'
      fullPath: '/components/input'
      preLoaderRoute: typeof ComponentsInputLazyRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/icon-button': {
      id: '/components/icon-button'
      path: '/icon-button'
      fullPath: '/components/icon-button'
      preLoaderRoute: typeof ComponentsIconButtonLazyRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/icon': {
      id: '/components/icon'
      path: '/icon'
      fullPath: '/components/icon'
      preLoaderRoute: typeof ComponentsIconLazyRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/drawer': {
      id: '/components/drawer'
      path: '/drawer'
      fullPath: '/components/drawer'
      preLoaderRoute: typeof ComponentsDrawerLazyRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/dialog': {
      id: '/components/dialog'
      path: '/dialog'
      fullPath: '/components/dialog'
      preLoaderRoute: typeof ComponentsDialogLazyRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/color': {
      id: '/components/color'
      path: '/color'
      fullPath: '/components/color'
      preLoaderRoute: typeof ComponentsColorLazyRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/card': {
      id: '/components/card'
      path: '/card'
      fullPath: '/components/card'
      preLoaderRoute: typeof ComponentsCardLazyRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/button': {
      id: '/components/button'
      path: '/button'
      fullPath: '/components/button'
      preLoaderRoute: typeof ComponentsButtonLazyRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/breakpoints': {
      id: '/components/breakpoints'
      path: '/breakpoints'
      fullPath: '/components/breakpoints'
      preLoaderRoute: typeof ComponentsBreakpointsLazyRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/badge': {
      id: '/components/badge'
      path: '/badge'
      fullPath: '/components/badge'
      preLoaderRoute: typeof ComponentsBadgeLazyRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/audio': {
      id: '/components/audio'
      path: '/audio'
      fullPath: '/components/audio'
      preLoaderRoute: typeof ComponentsAudioLazyRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/animation': {
      id: '/components/animation'
      path: '/animation'
      fullPath: '/components/animation'
      preLoaderRoute: typeof ComponentsAnimationLazyRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/thematic': {
      id: '/components/thematic'
      path: '/thematic'
      fullPath: '/components/thematic'
      preLoaderRoute: typeof ComponentsThematicRouteRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/_app/songs/': {
      id: '/_app/songs/'
      path: '/songs'
      fullPath: '/songs/'
      preLoaderRoute: typeof AppSongsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/library/': {
      id: '/_app/library/'
      path: '/library'
      fullPath: '/library/'
      preLoaderRoute: typeof AppLibraryIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/characters/': {
      id: '/_app/characters/'
      path: '/characters'
      fullPath: '/characters/'
      preLoaderRoute: typeof AppCharactersIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/components/thematic/vines': {
      id: '/components/thematic/vines'
      path: '/vines'
      fullPath: '/components/thematic/vines'
      preLoaderRoute: typeof ComponentsThematicVinesLazyRouteImport
      parentRoute: typeof ComponentsThematicRouteRoute
    }
    '/components/thematic/sin-glyph': {
      id: '/components/thematic/sin-glyph'
      path: '/sin-glyph'
      fullPath: '/components/thematic/sin-glyph'
      preLoaderRoute: typeof ComponentsThematicSinGlyphLazyRouteImport
      parentRoute: typeof ComponentsThematicRouteRoute
    }
    '/components/thematic/ornament': {
      id: '/components/thematic/ornament'
      path: '/ornament'
      fullPath: '/components/thematic/ornament'
      preLoaderRoute: typeof ComponentsThematicOrnamentLazyRouteImport
      parentRoute: typeof ComponentsThematicRouteRoute
    }
    '/components/thematic/clockwork-spinner': {
      id: '/components/thematic/clockwork-spinner'
      path: '/clockwork-spinner'
      fullPath: '/components/thematic/clockwork-spinner'
      preLoaderRoute: typeof ComponentsThematicClockworkSpinnerLazyRouteImport
      parentRoute: typeof ComponentsThematicRouteRoute
    }
    '/components/thematic/clockwork-ornament': {
      id: '/components/thematic/clockwork-ornament'
      path: '/clockwork-ornament'
      fullPath: '/components/thematic/clockwork-ornament'
      preLoaderRoute: typeof ComponentsThematicClockworkOrnamentLazyRouteImport
      parentRoute: typeof ComponentsThematicRouteRoute
    }
    '/components/thematic/clock-face': {
      id: '/components/thematic/clock-face'
      path: '/clock-face'
      fullPath: '/components/thematic/clock-face'
      preLoaderRoute: typeof ComponentsThematicClockFaceLazyRouteImport
      parentRoute: typeof ComponentsThematicRouteRoute
    }
    '/_app/characters/$characterId': {
      id: '/_app/characters/$characterId'
      path: '/characters/$characterId'
      fullPath: '/characters/$characterId'
      preLoaderRoute: typeof AppCharactersCharacterIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/library/$seriesId/': {
      id: '/_app/library/$seriesId/'
      path: '/library/$seriesId'
      fullPath: '/library/$seriesId/'
      preLoaderRoute: typeof AppLibrarySeriesIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/library/$seriesId/$volumeId/': {
      id: '/_app/library/$seriesId/$volumeId/'
      path: '/library/$seriesId/$volumeId'
      fullPath: '/library/$seriesId/$volumeId/'
      preLoaderRoute: typeof AppLibrarySeriesIdVolumeIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/library/$seriesId/$volumeId/$chapterId/': {
      id: '/_app/library/$seriesId/$volumeId/$chapterId/'
      path: '/library/$seriesId/$volumeId/$chapterId'
      fullPath: '/library/$seriesId/$volumeId/$chapterId/'
      preLoaderRoute: typeof AppLibrarySeriesIdVolumeIdChapterIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/library/$seriesId/$volumeId/$chapterId/$pageNumber': {
      id: '/_app/library/$seriesId/$volumeId/$chapterId/$pageNumber'
      path: '/library/$seriesId/$volumeId/$chapterId/$pageNumber'
      fullPath: '/library/$seriesId/$volumeId/$chapterId/$pageNumber'
      preLoaderRoute: typeof AppLibrarySeriesIdVolumeIdChapterIdPageNumberRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppCharactersCharacterIdRoute: typeof AppCharactersCharacterIdRoute
  AppCharactersIndexRoute: typeof AppCharactersIndexRoute
  AppLibraryIndexRoute: typeof AppLibraryIndexRoute
  AppSongsIndexRoute: typeof AppSongsIndexRoute
  AppLibrarySeriesIdIndexRoute: typeof AppLibrarySeriesIdIndexRoute
  AppLibrarySeriesIdVolumeIdIndexRoute: typeof AppLibrarySeriesIdVolumeIdIndexRoute
  AppLibrarySeriesIdVolumeIdChapterIdPageNumberRoute: typeof AppLibrarySeriesIdVolumeIdChapterIdPageNumberRoute
  AppLibrarySeriesIdVolumeIdChapterIdIndexRoute: typeof AppLibrarySeriesIdVolumeIdChapterIdIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppCharactersCharacterIdRoute: AppCharactersCharacterIdRoute,
  AppCharactersIndexRoute: AppCharactersIndexRoute,
  AppLibraryIndexRoute: AppLibraryIndexRoute,
  AppSongsIndexRoute: AppSongsIndexRoute,
  AppLibrarySeriesIdIndexRoute: AppLibrarySeriesIdIndexRoute,
  AppLibrarySeriesIdVolumeIdIndexRoute: AppLibrarySeriesIdVolumeIdIndexRoute,
  AppLibrarySeriesIdVolumeIdChapterIdPageNumberRoute:
    AppLibrarySeriesIdVolumeIdChapterIdPageNumberRoute,
  AppLibrarySeriesIdVolumeIdChapterIdIndexRoute:
    AppLibrarySeriesIdVolumeIdChapterIdIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface ComponentsThematicRouteRouteChildren {
  ComponentsThematicClockFaceLazyRoute: typeof ComponentsThematicClockFaceLazyRoute
  ComponentsThematicClockworkOrnamentLazyRoute: typeof ComponentsThematicClockworkOrnamentLazyRoute
  ComponentsThematicClockworkSpinnerLazyRoute: typeof ComponentsThematicClockworkSpinnerLazyRoute
  ComponentsThematicOrnamentLazyRoute: typeof ComponentsThematicOrnamentLazyRoute
  ComponentsThematicSinGlyphLazyRoute: typeof ComponentsThematicSinGlyphLazyRoute
  ComponentsThematicVinesLazyRoute: typeof ComponentsThematicVinesLazyRoute
}

const ComponentsThematicRouteRouteChildren: ComponentsThematicRouteRouteChildren =
  {
    ComponentsThematicClockFaceLazyRoute: ComponentsThematicClockFaceLazyRoute,
    ComponentsThematicClockworkOrnamentLazyRoute:
      ComponentsThematicClockworkOrnamentLazyRoute,
    ComponentsThematicClockworkSpinnerLazyRoute:
      ComponentsThematicClockworkSpinnerLazyRoute,
    ComponentsThematicOrnamentLazyRoute: ComponentsThematicOrnamentLazyRoute,
    ComponentsThematicSinGlyphLazyRoute: ComponentsThematicSinGlyphLazyRoute,
    ComponentsThematicVinesLazyRoute: ComponentsThematicVinesLazyRoute,
  }

const ComponentsThematicRouteRouteWithChildren =
  ComponentsThematicRouteRoute._addFileChildren(
    ComponentsThematicRouteRouteChildren,
  )

interface ComponentsRouteRouteChildren {
  ComponentsThematicRouteRoute: typeof ComponentsThematicRouteRouteWithChildren
  ComponentsAnimationLazyRoute: typeof ComponentsAnimationLazyRoute
  ComponentsAudioLazyRoute: typeof ComponentsAudioLazyRoute
  ComponentsBadgeLazyRoute: typeof ComponentsBadgeLazyRoute
  ComponentsBreakpointsLazyRoute: typeof ComponentsBreakpointsLazyRoute
  ComponentsButtonLazyRoute: typeof ComponentsButtonLazyRoute
  ComponentsCardLazyRoute: typeof ComponentsCardLazyRoute
  ComponentsColorLazyRoute: typeof ComponentsColorLazyRoute
  ComponentsDialogLazyRoute: typeof ComponentsDialogLazyRoute
  ComponentsDrawerLazyRoute: typeof ComponentsDrawerLazyRoute
  ComponentsIconLazyRoute: typeof ComponentsIconLazyRoute
  ComponentsIconButtonLazyRoute: typeof ComponentsIconButtonLazyRoute
  ComponentsInputLazyRoute: typeof ComponentsInputLazyRoute
  ComponentsLinkLazyRoute: typeof ComponentsLinkLazyRoute
  ComponentsMenuLazyRoute: typeof ComponentsMenuLazyRoute
  ComponentsPaginationLazyRoute: typeof ComponentsPaginationLazyRoute
  ComponentsProgressLazyRoute: typeof ComponentsProgressLazyRoute
  ComponentsQrCodeLazyRoute: typeof ComponentsQrCodeLazyRoute
  ComponentsQrScannerLazyRoute: typeof ComponentsQrScannerLazyRoute
  ComponentsScrollAreaLazyRoute: typeof ComponentsScrollAreaLazyRoute
  ComponentsSearchLazyRoute: typeof ComponentsSearchLazyRoute
  ComponentsSkeletonLazyRoute: typeof ComponentsSkeletonLazyRoute
  ComponentsSliderLazyRoute: typeof ComponentsSliderLazyRoute
  ComponentsSwitchLazyRoute: typeof ComponentsSwitchLazyRoute
  ComponentsTabsLazyRoute: typeof ComponentsTabsLazyRoute
  ComponentsToastLazyRoute: typeof ComponentsToastLazyRoute
  ComponentsTooltipLazyRoute: typeof ComponentsTooltipLazyRoute
  ComponentsTypographyLazyRoute: typeof ComponentsTypographyLazyRoute
  ComponentsIndexRoute: typeof ComponentsIndexRoute
}

const ComponentsRouteRouteChildren: ComponentsRouteRouteChildren = {
  ComponentsThematicRouteRoute: ComponentsThematicRouteRouteWithChildren,
  ComponentsAnimationLazyRoute: ComponentsAnimationLazyRoute,
  ComponentsAudioLazyRoute: ComponentsAudioLazyRoute,
  ComponentsBadgeLazyRoute: ComponentsBadgeLazyRoute,
  ComponentsBreakpointsLazyRoute: ComponentsBreakpointsLazyRoute,
  ComponentsButtonLazyRoute: ComponentsButtonLazyRoute,
  ComponentsCardLazyRoute: ComponentsCardLazyRoute,
  ComponentsColorLazyRoute: ComponentsColorLazyRoute,
  ComponentsDialogLazyRoute: ComponentsDialogLazyRoute,
  ComponentsDrawerLazyRoute: ComponentsDrawerLazyRoute,
  ComponentsIconLazyRoute: ComponentsIconLazyRoute,
  ComponentsIconButtonLazyRoute: ComponentsIconButtonLazyRoute,
  ComponentsInputLazyRoute: ComponentsInputLazyRoute,
  ComponentsLinkLazyRoute: ComponentsLinkLazyRoute,
  ComponentsMenuLazyRoute: ComponentsMenuLazyRoute,
  ComponentsPaginationLazyRoute: ComponentsPaginationLazyRoute,
  ComponentsProgressLazyRoute: ComponentsProgressLazyRoute,
  ComponentsQrCodeLazyRoute: ComponentsQrCodeLazyRoute,
  ComponentsQrScannerLazyRoute: ComponentsQrScannerLazyRoute,
  ComponentsScrollAreaLazyRoute: ComponentsScrollAreaLazyRoute,
  ComponentsSearchLazyRoute: ComponentsSearchLazyRoute,
  ComponentsSkeletonLazyRoute: ComponentsSkeletonLazyRoute,
  ComponentsSliderLazyRoute: ComponentsSliderLazyRoute,
  ComponentsSwitchLazyRoute: ComponentsSwitchLazyRoute,
  ComponentsTabsLazyRoute: ComponentsTabsLazyRoute,
  ComponentsToastLazyRoute: ComponentsToastLazyRoute,
  ComponentsTooltipLazyRoute: ComponentsTooltipLazyRoute,
  ComponentsTypographyLazyRoute: ComponentsTypographyLazyRoute,
  ComponentsIndexRoute: ComponentsIndexRoute,
}

const ComponentsRouteRouteWithChildren = ComponentsRouteRoute._addFileChildren(
  ComponentsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  ComponentsRouteRoute: ComponentsRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
