/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as ComponentsRouteRouteImport } from './routes/components/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as ComponentsIndexRouteImport } from './routes/components/index'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSongsIndexRouteImport } from './routes/_app/songs/index'
import { Route as AppLibraryIndexRouteImport } from './routes/_app/library/index'
import { Route as AppCharactersIndexRouteImport } from './routes/_app/characters/index'
import { Route as AppCharactersCharacterIdRouteImport } from './routes/_app/characters/$characterId'
import { Route as AppLibrarySeriesIdIndexRouteImport } from './routes/_app/library/$seriesId/index'
import { Route as AppLibrarySeriesIdVolumeIdIndexRouteImport } from './routes/_app/library/$seriesId/$volumeId/index'
import { Route as AppLibrarySeriesIdVolumeIdChapterIdIndexRouteImport } from './routes/_app/library/$seriesId/$volumeId/$chapterId/index'
import { Route as AppLibrarySeriesIdVolumeIdChapterIdPageNumberRouteImport } from './routes/_app/library/$seriesId/$volumeId/$chapterId/$pageNumber'

const ComponentsSlugLazyRouteImport = createFileRoute('/components/$slug')()

const ComponentsRouteRoute = ComponentsRouteRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsIndexRoute = ComponentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ComponentsRouteRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const ComponentsSlugLazyRoute = ComponentsSlugLazyRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ComponentsRouteRoute,
} as any).lazy(() =>
  import('./routes/components/$slug.lazy').then((d) => d.Route),
)
const AppSongsIndexRoute = AppSongsIndexRouteImport.update({
  id: '/songs/',
  path: '/songs/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLibraryIndexRoute = AppLibraryIndexRouteImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCharactersIndexRoute = AppCharactersIndexRouteImport.update({
  id: '/characters/',
  path: '/characters/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCharactersCharacterIdRoute =
  AppCharactersCharacterIdRouteImport.update({
    id: '/characters/$characterId',
    path: '/characters/$characterId',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppLibrarySeriesIdIndexRoute = AppLibrarySeriesIdIndexRouteImport.update({
  id: '/library/$seriesId/',
  path: '/library/$seriesId/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLibrarySeriesIdVolumeIdIndexRoute =
  AppLibrarySeriesIdVolumeIdIndexRouteImport.update({
    id: '/library/$seriesId/$volumeId/',
    path: '/library/$seriesId/$volumeId/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppLibrarySeriesIdVolumeIdChapterIdIndexRoute =
  AppLibrarySeriesIdVolumeIdChapterIdIndexRouteImport.update({
    id: '/library/$seriesId/$volumeId/$chapterId/',
    path: '/library/$seriesId/$volumeId/$chapterId/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppLibrarySeriesIdVolumeIdChapterIdPageNumberRoute =
  AppLibrarySeriesIdVolumeIdChapterIdPageNumberRouteImport.update({
    id: '/library/$seriesId/$volumeId/$chapterId/$pageNumber',
    path: '/library/$seriesId/$volumeId/$chapterId/$pageNumber',
    getParentRoute: () => AppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/components': typeof ComponentsRouteRouteWithChildren
  '/components/$slug': typeof ComponentsSlugLazyRoute
  '/components/': typeof ComponentsIndexRoute
  '/characters/$characterId': typeof AppCharactersCharacterIdRoute
  '/characters/': typeof AppCharactersIndexRoute
  '/library/': typeof AppLibraryIndexRoute
  '/songs/': typeof AppSongsIndexRoute
  '/library/$seriesId/': typeof AppLibrarySeriesIdIndexRoute
  '/library/$seriesId/$volumeId/': typeof AppLibrarySeriesIdVolumeIdIndexRoute
  '/library/$seriesId/$volumeId/$chapterId/$pageNumber': typeof AppLibrarySeriesIdVolumeIdChapterIdPageNumberRoute
  '/library/$seriesId/$volumeId/$chapterId/': typeof AppLibrarySeriesIdVolumeIdChapterIdIndexRoute
}
export interface FileRoutesByTo {
  '/components/$slug': typeof ComponentsSlugLazyRoute
  '/': typeof AppIndexRoute
  '/components': typeof ComponentsIndexRoute
  '/characters/$characterId': typeof AppCharactersCharacterIdRoute
  '/characters': typeof AppCharactersIndexRoute
  '/library': typeof AppLibraryIndexRoute
  '/songs': typeof AppSongsIndexRoute
  '/library/$seriesId': typeof AppLibrarySeriesIdIndexRoute
  '/library/$seriesId/$volumeId': typeof AppLibrarySeriesIdVolumeIdIndexRoute
  '/library/$seriesId/$volumeId/$chapterId/$pageNumber': typeof AppLibrarySeriesIdVolumeIdChapterIdPageNumberRoute
  '/library/$seriesId/$volumeId/$chapterId': typeof AppLibrarySeriesIdVolumeIdChapterIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/components': typeof ComponentsRouteRouteWithChildren
  '/components/$slug': typeof ComponentsSlugLazyRoute
  '/_app/': typeof AppIndexRoute
  '/components/': typeof ComponentsIndexRoute
  '/_app/characters/$characterId': typeof AppCharactersCharacterIdRoute
  '/_app/characters/': typeof AppCharactersIndexRoute
  '/_app/library/': typeof AppLibraryIndexRoute
  '/_app/songs/': typeof AppSongsIndexRoute
  '/_app/library/$seriesId/': typeof AppLibrarySeriesIdIndexRoute
  '/_app/library/$seriesId/$volumeId/': typeof AppLibrarySeriesIdVolumeIdIndexRoute
  '/_app/library/$seriesId/$volumeId/$chapterId/$pageNumber': typeof AppLibrarySeriesIdVolumeIdChapterIdPageNumberRoute
  '/_app/library/$seriesId/$volumeId/$chapterId/': typeof AppLibrarySeriesIdVolumeIdChapterIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/components'
    | '/components/$slug'
    | '/components/'
    | '/characters/$characterId'
    | '/characters/'
    | '/library/'
    | '/songs/'
    | '/library/$seriesId/'
    | '/library/$seriesId/$volumeId/'
    | '/library/$seriesId/$volumeId/$chapterId/$pageNumber'
    | '/library/$seriesId/$volumeId/$chapterId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/components/$slug'
    | '/'
    | '/components'
    | '/characters/$characterId'
    | '/characters'
    | '/library'
    | '/songs'
    | '/library/$seriesId'
    | '/library/$seriesId/$volumeId'
    | '/library/$seriesId/$volumeId/$chapterId/$pageNumber'
    | '/library/$seriesId/$volumeId/$chapterId'
  id:
    | '__root__'
    | '/_app'
    | '/components'
    | '/components/$slug'
    | '/_app/'
    | '/components/'
    | '/_app/characters/$characterId'
    | '/_app/characters/'
    | '/_app/library/'
    | '/_app/songs/'
    | '/_app/library/$seriesId/'
    | '/_app/library/$seriesId/$volumeId/'
    | '/_app/library/$seriesId/$volumeId/$chapterId/$pageNumber'
    | '/_app/library/$seriesId/$volumeId/$chapterId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  ComponentsRouteRoute: typeof ComponentsRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/components': {
      id: '/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/': {
      id: '/components/'
      path: '/'
      fullPath: '/components/'
      preLoaderRoute: typeof ComponentsIndexRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/components/$slug': {
      id: '/components/$slug'
      path: '/$slug'
      fullPath: '/components/$slug'
      preLoaderRoute: typeof ComponentsSlugLazyRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/_app/songs/': {
      id: '/_app/songs/'
      path: '/songs'
      fullPath: '/songs/'
      preLoaderRoute: typeof AppSongsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/library/': {
      id: '/_app/library/'
      path: '/library'
      fullPath: '/library/'
      preLoaderRoute: typeof AppLibraryIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/characters/': {
      id: '/_app/characters/'
      path: '/characters'
      fullPath: '/characters/'
      preLoaderRoute: typeof AppCharactersIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/characters/$characterId': {
      id: '/_app/characters/$characterId'
      path: '/characters/$characterId'
      fullPath: '/characters/$characterId'
      preLoaderRoute: typeof AppCharactersCharacterIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/library/$seriesId/': {
      id: '/_app/library/$seriesId/'
      path: '/library/$seriesId'
      fullPath: '/library/$seriesId/'
      preLoaderRoute: typeof AppLibrarySeriesIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/library/$seriesId/$volumeId/': {
      id: '/_app/library/$seriesId/$volumeId/'
      path: '/library/$seriesId/$volumeId'
      fullPath: '/library/$seriesId/$volumeId/'
      preLoaderRoute: typeof AppLibrarySeriesIdVolumeIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/library/$seriesId/$volumeId/$chapterId/': {
      id: '/_app/library/$seriesId/$volumeId/$chapterId/'
      path: '/library/$seriesId/$volumeId/$chapterId'
      fullPath: '/library/$seriesId/$volumeId/$chapterId/'
      preLoaderRoute: typeof AppLibrarySeriesIdVolumeIdChapterIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/library/$seriesId/$volumeId/$chapterId/$pageNumber': {
      id: '/_app/library/$seriesId/$volumeId/$chapterId/$pageNumber'
      path: '/library/$seriesId/$volumeId/$chapterId/$pageNumber'
      fullPath: '/library/$seriesId/$volumeId/$chapterId/$pageNumber'
      preLoaderRoute: typeof AppLibrarySeriesIdVolumeIdChapterIdPageNumberRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppCharactersCharacterIdRoute: typeof AppCharactersCharacterIdRoute
  AppCharactersIndexRoute: typeof AppCharactersIndexRoute
  AppLibraryIndexRoute: typeof AppLibraryIndexRoute
  AppSongsIndexRoute: typeof AppSongsIndexRoute
  AppLibrarySeriesIdIndexRoute: typeof AppLibrarySeriesIdIndexRoute
  AppLibrarySeriesIdVolumeIdIndexRoute: typeof AppLibrarySeriesIdVolumeIdIndexRoute
  AppLibrarySeriesIdVolumeIdChapterIdPageNumberRoute: typeof AppLibrarySeriesIdVolumeIdChapterIdPageNumberRoute
  AppLibrarySeriesIdVolumeIdChapterIdIndexRoute: typeof AppLibrarySeriesIdVolumeIdChapterIdIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppCharactersCharacterIdRoute: AppCharactersCharacterIdRoute,
  AppCharactersIndexRoute: AppCharactersIndexRoute,
  AppLibraryIndexRoute: AppLibraryIndexRoute,
  AppSongsIndexRoute: AppSongsIndexRoute,
  AppLibrarySeriesIdIndexRoute: AppLibrarySeriesIdIndexRoute,
  AppLibrarySeriesIdVolumeIdIndexRoute: AppLibrarySeriesIdVolumeIdIndexRoute,
  AppLibrarySeriesIdVolumeIdChapterIdPageNumberRoute:
    AppLibrarySeriesIdVolumeIdChapterIdPageNumberRoute,
  AppLibrarySeriesIdVolumeIdChapterIdIndexRoute:
    AppLibrarySeriesIdVolumeIdChapterIdIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface ComponentsRouteRouteChildren {
  ComponentsSlugLazyRoute: typeof ComponentsSlugLazyRoute
  ComponentsIndexRoute: typeof ComponentsIndexRoute
}

const ComponentsRouteRouteChildren: ComponentsRouteRouteChildren = {
  ComponentsSlugLazyRoute: ComponentsSlugLazyRoute,
  ComponentsIndexRoute: ComponentsIndexRoute,
}

const ComponentsRouteRouteWithChildren = ComponentsRouteRoute._addFileChildren(
  ComponentsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  ComponentsRouteRoute: ComponentsRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
