/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as ComponentsRouteRouteImport } from './routes/components/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComponentsIndexRouteImport } from './routes/components/index'
import { Route as AppLibraryIndexRouteImport } from './routes/_app/library/index'
import { Route as AppLibrarySeriesIdIndexRouteImport } from './routes/_app/library/$seriesId/index'
import { Route as AppLibrarySeriesIdVolumeIdIndexRouteImport } from './routes/_app/library/$seriesId/$volumeId/index'
import { Route as AppLibrarySeriesIdVolumeIdChapterIdRouteImport } from './routes/_app/library/$seriesId/$volumeId/$chapterId'

const ComponentsTypographyLazyRouteImport = createFileRoute(
  '/components/typography',
)()
const ComponentsTooltipLazyRouteImport = createFileRoute(
  '/components/tooltip',
)()
const ComponentsToastLazyRouteImport = createFileRoute('/components/toast')()
const ComponentsTabsLazyRouteImport = createFileRoute('/components/tabs')()
const ComponentsSwitchLazyRouteImport = createFileRoute('/components/switch')()
const ComponentsSliderLazyRouteImport = createFileRoute('/components/slider')()
const ComponentsSkeletonLazyRouteImport = createFileRoute(
  '/components/skeleton',
)()
const ComponentsScrollAreaLazyRouteImport = createFileRoute(
  '/components/scroll-area',
)()
const ComponentsProgressLazyRouteImport = createFileRoute(
  '/components/progress',
)()
const ComponentsMenuLazyRouteImport = createFileRoute('/components/menu')()
const ComponentsInputLazyRouteImport = createFileRoute('/components/input')()
const ComponentsIconButtonLazyRouteImport = createFileRoute(
  '/components/icon-button',
)()
const ComponentsIconLazyRouteImport = createFileRoute('/components/icon')()
const ComponentsDrawerLazyRouteImport = createFileRoute('/components/drawer')()
const ComponentsDialogLazyRouteImport = createFileRoute('/components/dialog')()
const ComponentsCardLazyRouteImport = createFileRoute('/components/card')()
const ComponentsButtonLazyRouteImport = createFileRoute('/components/button')()
const ComponentsBadgeLazyRouteImport = createFileRoute('/components/badge')()

const ComponentsRouteRoute = ComponentsRouteRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsIndexRoute = ComponentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ComponentsRouteRoute,
} as any)
const ComponentsTypographyLazyRoute =
  ComponentsTypographyLazyRouteImport.update({
    id: '/typography',
    path: '/typography',
    getParentRoute: () => ComponentsRouteRoute,
  } as any).lazy(() =>
    import('./routes/components/typography.lazy').then((d) => d.Route),
  )
const ComponentsTooltipLazyRoute = ComponentsTooltipLazyRouteImport.update({
  id: '/tooltip',
  path: '/tooltip',
  getParentRoute: () => ComponentsRouteRoute,
} as any).lazy(() =>
  import('./routes/components/tooltip.lazy').then((d) => d.Route),
)
const ComponentsToastLazyRoute = ComponentsToastLazyRouteImport.update({
  id: '/toast',
  path: '/toast',
  getParentRoute: () => ComponentsRouteRoute,
} as any).lazy(() =>
  import('./routes/components/toast.lazy').then((d) => d.Route),
)
const ComponentsTabsLazyRoute = ComponentsTabsLazyRouteImport.update({
  id: '/tabs',
  path: '/tabs',
  getParentRoute: () => ComponentsRouteRoute,
} as any).lazy(() =>
  import('./routes/components/tabs.lazy').then((d) => d.Route),
)
const ComponentsSwitchLazyRoute = ComponentsSwitchLazyRouteImport.update({
  id: '/switch',
  path: '/switch',
  getParentRoute: () => ComponentsRouteRoute,
} as any).lazy(() =>
  import('./routes/components/switch.lazy').then((d) => d.Route),
)
const ComponentsSliderLazyRoute = ComponentsSliderLazyRouteImport.update({
  id: '/slider',
  path: '/slider',
  getParentRoute: () => ComponentsRouteRoute,
} as any).lazy(() =>
  import('./routes/components/slider.lazy').then((d) => d.Route),
)
const ComponentsSkeletonLazyRoute = ComponentsSkeletonLazyRouteImport.update({
  id: '/skeleton',
  path: '/skeleton',
  getParentRoute: () => ComponentsRouteRoute,
} as any).lazy(() =>
  import('./routes/components/skeleton.lazy').then((d) => d.Route),
)
const ComponentsScrollAreaLazyRoute =
  ComponentsScrollAreaLazyRouteImport.update({
    id: '/scroll-area',
    path: '/scroll-area',
    getParentRoute: () => ComponentsRouteRoute,
  } as any).lazy(() =>
    import('./routes/components/scroll-area.lazy').then((d) => d.Route),
  )
const ComponentsProgressLazyRoute = ComponentsProgressLazyRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => ComponentsRouteRoute,
} as any).lazy(() =>
  import('./routes/components/progress.lazy').then((d) => d.Route),
)
const ComponentsMenuLazyRoute = ComponentsMenuLazyRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => ComponentsRouteRoute,
} as any).lazy(() =>
  import('./routes/components/menu.lazy').then((d) => d.Route),
)
const ComponentsInputLazyRoute = ComponentsInputLazyRouteImport.update({
  id: '/input',
  path: '/input',
  getParentRoute: () => ComponentsRouteRoute,
} as any).lazy(() =>
  import('./routes/components/input.lazy').then((d) => d.Route),
)
const ComponentsIconButtonLazyRoute =
  ComponentsIconButtonLazyRouteImport.update({
    id: '/icon-button',
    path: '/icon-button',
    getParentRoute: () => ComponentsRouteRoute,
  } as any).lazy(() =>
    import('./routes/components/icon-button.lazy').then((d) => d.Route),
  )
const ComponentsIconLazyRoute = ComponentsIconLazyRouteImport.update({
  id: '/icon',
  path: '/icon',
  getParentRoute: () => ComponentsRouteRoute,
} as any).lazy(() =>
  import('./routes/components/icon.lazy').then((d) => d.Route),
)
const ComponentsDrawerLazyRoute = ComponentsDrawerLazyRouteImport.update({
  id: '/drawer',
  path: '/drawer',
  getParentRoute: () => ComponentsRouteRoute,
} as any).lazy(() =>
  import('./routes/components/drawer.lazy').then((d) => d.Route),
)
const ComponentsDialogLazyRoute = ComponentsDialogLazyRouteImport.update({
  id: '/dialog',
  path: '/dialog',
  getParentRoute: () => ComponentsRouteRoute,
} as any).lazy(() =>
  import('./routes/components/dialog.lazy').then((d) => d.Route),
)
const ComponentsCardLazyRoute = ComponentsCardLazyRouteImport.update({
  id: '/card',
  path: '/card',
  getParentRoute: () => ComponentsRouteRoute,
} as any).lazy(() =>
  import('./routes/components/card.lazy').then((d) => d.Route),
)
const ComponentsButtonLazyRoute = ComponentsButtonLazyRouteImport.update({
  id: '/button',
  path: '/button',
  getParentRoute: () => ComponentsRouteRoute,
} as any).lazy(() =>
  import('./routes/components/button.lazy').then((d) => d.Route),
)
const ComponentsBadgeLazyRoute = ComponentsBadgeLazyRouteImport.update({
  id: '/badge',
  path: '/badge',
  getParentRoute: () => ComponentsRouteRoute,
} as any).lazy(() =>
  import('./routes/components/badge.lazy').then((d) => d.Route),
)
const AppLibraryIndexRoute = AppLibraryIndexRouteImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLibrarySeriesIdIndexRoute = AppLibrarySeriesIdIndexRouteImport.update({
  id: '/library/$seriesId/',
  path: '/library/$seriesId/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLibrarySeriesIdVolumeIdIndexRoute =
  AppLibrarySeriesIdVolumeIdIndexRouteImport.update({
    id: '/library/$seriesId/$volumeId/',
    path: '/library/$seriesId/$volumeId/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppLibrarySeriesIdVolumeIdChapterIdRoute =
  AppLibrarySeriesIdVolumeIdChapterIdRouteImport.update({
    id: '/library/$seriesId/$volumeId/$chapterId',
    path: '/library/$seriesId/$volumeId/$chapterId',
    getParentRoute: () => AppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/components': typeof ComponentsRouteRouteWithChildren
  '/components/badge': typeof ComponentsBadgeLazyRoute
  '/components/button': typeof ComponentsButtonLazyRoute
  '/components/card': typeof ComponentsCardLazyRoute
  '/components/dialog': typeof ComponentsDialogLazyRoute
  '/components/drawer': typeof ComponentsDrawerLazyRoute
  '/components/icon': typeof ComponentsIconLazyRoute
  '/components/icon-button': typeof ComponentsIconButtonLazyRoute
  '/components/input': typeof ComponentsInputLazyRoute
  '/components/menu': typeof ComponentsMenuLazyRoute
  '/components/progress': typeof ComponentsProgressLazyRoute
  '/components/scroll-area': typeof ComponentsScrollAreaLazyRoute
  '/components/skeleton': typeof ComponentsSkeletonLazyRoute
  '/components/slider': typeof ComponentsSliderLazyRoute
  '/components/switch': typeof ComponentsSwitchLazyRoute
  '/components/tabs': typeof ComponentsTabsLazyRoute
  '/components/toast': typeof ComponentsToastLazyRoute
  '/components/tooltip': typeof ComponentsTooltipLazyRoute
  '/components/typography': typeof ComponentsTypographyLazyRoute
  '/components/': typeof ComponentsIndexRoute
  '/library/': typeof AppLibraryIndexRoute
  '/library/$seriesId/': typeof AppLibrarySeriesIdIndexRoute
  '/library/$seriesId/$volumeId/$chapterId': typeof AppLibrarySeriesIdVolumeIdChapterIdRoute
  '/library/$seriesId/$volumeId/': typeof AppLibrarySeriesIdVolumeIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/components/badge': typeof ComponentsBadgeLazyRoute
  '/components/button': typeof ComponentsButtonLazyRoute
  '/components/card': typeof ComponentsCardLazyRoute
  '/components/dialog': typeof ComponentsDialogLazyRoute
  '/components/drawer': typeof ComponentsDrawerLazyRoute
  '/components/icon': typeof ComponentsIconLazyRoute
  '/components/icon-button': typeof ComponentsIconButtonLazyRoute
  '/components/input': typeof ComponentsInputLazyRoute
  '/components/menu': typeof ComponentsMenuLazyRoute
  '/components/progress': typeof ComponentsProgressLazyRoute
  '/components/scroll-area': typeof ComponentsScrollAreaLazyRoute
  '/components/skeleton': typeof ComponentsSkeletonLazyRoute
  '/components/slider': typeof ComponentsSliderLazyRoute
  '/components/switch': typeof ComponentsSwitchLazyRoute
  '/components/tabs': typeof ComponentsTabsLazyRoute
  '/components/toast': typeof ComponentsToastLazyRoute
  '/components/tooltip': typeof ComponentsTooltipLazyRoute
  '/components/typography': typeof ComponentsTypographyLazyRoute
  '/components': typeof ComponentsIndexRoute
  '/library': typeof AppLibraryIndexRoute
  '/library/$seriesId': typeof AppLibrarySeriesIdIndexRoute
  '/library/$seriesId/$volumeId/$chapterId': typeof AppLibrarySeriesIdVolumeIdChapterIdRoute
  '/library/$seriesId/$volumeId': typeof AppLibrarySeriesIdVolumeIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/components': typeof ComponentsRouteRouteWithChildren
  '/components/badge': typeof ComponentsBadgeLazyRoute
  '/components/button': typeof ComponentsButtonLazyRoute
  '/components/card': typeof ComponentsCardLazyRoute
  '/components/dialog': typeof ComponentsDialogLazyRoute
  '/components/drawer': typeof ComponentsDrawerLazyRoute
  '/components/icon': typeof ComponentsIconLazyRoute
  '/components/icon-button': typeof ComponentsIconButtonLazyRoute
  '/components/input': typeof ComponentsInputLazyRoute
  '/components/menu': typeof ComponentsMenuLazyRoute
  '/components/progress': typeof ComponentsProgressLazyRoute
  '/components/scroll-area': typeof ComponentsScrollAreaLazyRoute
  '/components/skeleton': typeof ComponentsSkeletonLazyRoute
  '/components/slider': typeof ComponentsSliderLazyRoute
  '/components/switch': typeof ComponentsSwitchLazyRoute
  '/components/tabs': typeof ComponentsTabsLazyRoute
  '/components/toast': typeof ComponentsToastLazyRoute
  '/components/tooltip': typeof ComponentsTooltipLazyRoute
  '/components/typography': typeof ComponentsTypographyLazyRoute
  '/components/': typeof ComponentsIndexRoute
  '/_app/library/': typeof AppLibraryIndexRoute
  '/_app/library/$seriesId/': typeof AppLibrarySeriesIdIndexRoute
  '/_app/library/$seriesId/$volumeId/$chapterId': typeof AppLibrarySeriesIdVolumeIdChapterIdRoute
  '/_app/library/$seriesId/$volumeId/': typeof AppLibrarySeriesIdVolumeIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/components'
    | '/components/badge'
    | '/components/button'
    | '/components/card'
    | '/components/dialog'
    | '/components/drawer'
    | '/components/icon'
    | '/components/icon-button'
    | '/components/input'
    | '/components/menu'
    | '/components/progress'
    | '/components/scroll-area'
    | '/components/skeleton'
    | '/components/slider'
    | '/components/switch'
    | '/components/tabs'
    | '/components/toast'
    | '/components/tooltip'
    | '/components/typography'
    | '/components/'
    | '/library/'
    | '/library/$seriesId/'
    | '/library/$seriesId/$volumeId/$chapterId'
    | '/library/$seriesId/$volumeId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/components/badge'
    | '/components/button'
    | '/components/card'
    | '/components/dialog'
    | '/components/drawer'
    | '/components/icon'
    | '/components/icon-button'
    | '/components/input'
    | '/components/menu'
    | '/components/progress'
    | '/components/scroll-area'
    | '/components/skeleton'
    | '/components/slider'
    | '/components/switch'
    | '/components/tabs'
    | '/components/toast'
    | '/components/tooltip'
    | '/components/typography'
    | '/components'
    | '/library'
    | '/library/$seriesId'
    | '/library/$seriesId/$volumeId/$chapterId'
    | '/library/$seriesId/$volumeId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/components'
    | '/components/badge'
    | '/components/button'
    | '/components/card'
    | '/components/dialog'
    | '/components/drawer'
    | '/components/icon'
    | '/components/icon-button'
    | '/components/input'
    | '/components/menu'
    | '/components/progress'
    | '/components/scroll-area'
    | '/components/skeleton'
    | '/components/slider'
    | '/components/switch'
    | '/components/tabs'
    | '/components/toast'
    | '/components/tooltip'
    | '/components/typography'
    | '/components/'
    | '/_app/library/'
    | '/_app/library/$seriesId/'
    | '/_app/library/$seriesId/$volumeId/$chapterId'
    | '/_app/library/$seriesId/$volumeId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  ComponentsRouteRoute: typeof ComponentsRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/components': {
      id: '/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/': {
      id: '/components/'
      path: '/'
      fullPath: '/components/'
      preLoaderRoute: typeof ComponentsIndexRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/typography': {
      id: '/components/typography'
      path: '/typography'
      fullPath: '/components/typography'
      preLoaderRoute: typeof ComponentsTypographyLazyRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/tooltip': {
      id: '/components/tooltip'
      path: '/tooltip'
      fullPath: '/components/tooltip'
      preLoaderRoute: typeof ComponentsTooltipLazyRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/toast': {
      id: '/components/toast'
      path: '/toast'
      fullPath: '/components/toast'
      preLoaderRoute: typeof ComponentsToastLazyRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/tabs': {
      id: '/components/tabs'
      path: '/tabs'
      fullPath: '/components/tabs'
      preLoaderRoute: typeof ComponentsTabsLazyRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/switch': {
      id: '/components/switch'
      path: '/switch'
      fullPath: '/components/switch'
      preLoaderRoute: typeof ComponentsSwitchLazyRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/slider': {
      id: '/components/slider'
      path: '/slider'
      fullPath: '/components/slider'
      preLoaderRoute: typeof ComponentsSliderLazyRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/skeleton': {
      id: '/components/skeleton'
      path: '/skeleton'
      fullPath: '/components/skeleton'
      preLoaderRoute: typeof ComponentsSkeletonLazyRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/scroll-area': {
      id: '/components/scroll-area'
      path: '/scroll-area'
      fullPath: '/components/scroll-area'
      preLoaderRoute: typeof ComponentsScrollAreaLazyRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/progress': {
      id: '/components/progress'
      path: '/progress'
      fullPath: '/components/progress'
      preLoaderRoute: typeof ComponentsProgressLazyRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/menu': {
      id: '/components/menu'
      path: '/menu'
      fullPath: '/components/menu'
      preLoaderRoute: typeof ComponentsMenuLazyRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/input': {
      id: '/components/input'
      path: '/input'
      fullPath: '/components/input'
      preLoaderRoute: typeof ComponentsInputLazyRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/icon-button': {
      id: '/components/icon-button'
      path: '/icon-button'
      fullPath: '/components/icon-button'
      preLoaderRoute: typeof ComponentsIconButtonLazyRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/icon': {
      id: '/components/icon'
      path: '/icon'
      fullPath: '/components/icon'
      preLoaderRoute: typeof ComponentsIconLazyRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/drawer': {
      id: '/components/drawer'
      path: '/drawer'
      fullPath: '/components/drawer'
      preLoaderRoute: typeof ComponentsDrawerLazyRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/dialog': {
      id: '/components/dialog'
      path: '/dialog'
      fullPath: '/components/dialog'
      preLoaderRoute: typeof ComponentsDialogLazyRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/card': {
      id: '/components/card'
      path: '/card'
      fullPath: '/components/card'
      preLoaderRoute: typeof ComponentsCardLazyRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/button': {
      id: '/components/button'
      path: '/button'
      fullPath: '/components/button'
      preLoaderRoute: typeof ComponentsButtonLazyRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/components/badge': {
      id: '/components/badge'
      path: '/badge'
      fullPath: '/components/badge'
      preLoaderRoute: typeof ComponentsBadgeLazyRouteImport
      parentRoute: typeof ComponentsRouteRoute
    }
    '/_app/library/': {
      id: '/_app/library/'
      path: '/library'
      fullPath: '/library/'
      preLoaderRoute: typeof AppLibraryIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/library/$seriesId/': {
      id: '/_app/library/$seriesId/'
      path: '/library/$seriesId'
      fullPath: '/library/$seriesId/'
      preLoaderRoute: typeof AppLibrarySeriesIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/library/$seriesId/$volumeId/': {
      id: '/_app/library/$seriesId/$volumeId/'
      path: '/library/$seriesId/$volumeId'
      fullPath: '/library/$seriesId/$volumeId/'
      preLoaderRoute: typeof AppLibrarySeriesIdVolumeIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/library/$seriesId/$volumeId/$chapterId': {
      id: '/_app/library/$seriesId/$volumeId/$chapterId'
      path: '/library/$seriesId/$volumeId/$chapterId'
      fullPath: '/library/$seriesId/$volumeId/$chapterId'
      preLoaderRoute: typeof AppLibrarySeriesIdVolumeIdChapterIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppLibraryIndexRoute: typeof AppLibraryIndexRoute
  AppLibrarySeriesIdIndexRoute: typeof AppLibrarySeriesIdIndexRoute
  AppLibrarySeriesIdVolumeIdChapterIdRoute: typeof AppLibrarySeriesIdVolumeIdChapterIdRoute
  AppLibrarySeriesIdVolumeIdIndexRoute: typeof AppLibrarySeriesIdVolumeIdIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppLibraryIndexRoute: AppLibraryIndexRoute,
  AppLibrarySeriesIdIndexRoute: AppLibrarySeriesIdIndexRoute,
  AppLibrarySeriesIdVolumeIdChapterIdRoute:
    AppLibrarySeriesIdVolumeIdChapterIdRoute,
  AppLibrarySeriesIdVolumeIdIndexRoute: AppLibrarySeriesIdVolumeIdIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface ComponentsRouteRouteChildren {
  ComponentsBadgeLazyRoute: typeof ComponentsBadgeLazyRoute
  ComponentsButtonLazyRoute: typeof ComponentsButtonLazyRoute
  ComponentsCardLazyRoute: typeof ComponentsCardLazyRoute
  ComponentsDialogLazyRoute: typeof ComponentsDialogLazyRoute
  ComponentsDrawerLazyRoute: typeof ComponentsDrawerLazyRoute
  ComponentsIconLazyRoute: typeof ComponentsIconLazyRoute
  ComponentsIconButtonLazyRoute: typeof ComponentsIconButtonLazyRoute
  ComponentsInputLazyRoute: typeof ComponentsInputLazyRoute
  ComponentsMenuLazyRoute: typeof ComponentsMenuLazyRoute
  ComponentsProgressLazyRoute: typeof ComponentsProgressLazyRoute
  ComponentsScrollAreaLazyRoute: typeof ComponentsScrollAreaLazyRoute
  ComponentsSkeletonLazyRoute: typeof ComponentsSkeletonLazyRoute
  ComponentsSliderLazyRoute: typeof ComponentsSliderLazyRoute
  ComponentsSwitchLazyRoute: typeof ComponentsSwitchLazyRoute
  ComponentsTabsLazyRoute: typeof ComponentsTabsLazyRoute
  ComponentsToastLazyRoute: typeof ComponentsToastLazyRoute
  ComponentsTooltipLazyRoute: typeof ComponentsTooltipLazyRoute
  ComponentsTypographyLazyRoute: typeof ComponentsTypographyLazyRoute
  ComponentsIndexRoute: typeof ComponentsIndexRoute
}

const ComponentsRouteRouteChildren: ComponentsRouteRouteChildren = {
  ComponentsBadgeLazyRoute: ComponentsBadgeLazyRoute,
  ComponentsButtonLazyRoute: ComponentsButtonLazyRoute,
  ComponentsCardLazyRoute: ComponentsCardLazyRoute,
  ComponentsDialogLazyRoute: ComponentsDialogLazyRoute,
  ComponentsDrawerLazyRoute: ComponentsDrawerLazyRoute,
  ComponentsIconLazyRoute: ComponentsIconLazyRoute,
  ComponentsIconButtonLazyRoute: ComponentsIconButtonLazyRoute,
  ComponentsInputLazyRoute: ComponentsInputLazyRoute,
  ComponentsMenuLazyRoute: ComponentsMenuLazyRoute,
  ComponentsProgressLazyRoute: ComponentsProgressLazyRoute,
  ComponentsScrollAreaLazyRoute: ComponentsScrollAreaLazyRoute,
  ComponentsSkeletonLazyRoute: ComponentsSkeletonLazyRoute,
  ComponentsSliderLazyRoute: ComponentsSliderLazyRoute,
  ComponentsSwitchLazyRoute: ComponentsSwitchLazyRoute,
  ComponentsTabsLazyRoute: ComponentsTabsLazyRoute,
  ComponentsToastLazyRoute: ComponentsToastLazyRoute,
  ComponentsTooltipLazyRoute: ComponentsTooltipLazyRoute,
  ComponentsTypographyLazyRoute: ComponentsTypographyLazyRoute,
  ComponentsIndexRoute: ComponentsIndexRoute,
}

const ComponentsRouteRouteWithChildren = ComponentsRouteRoute._addFileChildren(
  ComponentsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  ComponentsRouteRoute: ComponentsRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
